### PR TITLE
Added a requirements.txt file

### PR DESCRIPTION
**Pull request by anomitra**
This adds a `requirements.txt` file to the project, so that users can just use a `pip install requirements.txt` to install all the dependencies for the project.

### CODE REVIEW

**Comment by zvodd** [comment]
How about just this for `requirements.txt`
```
lxml==4.2.5
Scrapy==1.5.1
SQLAlchemy==1.2.15
```

**Comment by anomitra** [comment]
I generated this using a fresh virtual environment and then doing `pip freeze`. I think this is the appropriate way of doing, although yours would probably work just as well!

**Comment by zvodd** [comment]
Alright then, I wasn't sure.

**Comment by eirnym** [comment]
> I generated this using a fresh virtual environment and then doing `pip freeze`. I think this is the appropriate way of doing, although yours would probably work just as well!

This is not. If you need just to update dependencies, you'll have a problem to guess what really do you need to update and what you shouldn't.

**Comment by anomitra** [comment]
Actually, it's not such a bad idea to pin the dependencies as well. Let's say you have `lxml==4.2.5` which depends on `somepackage`. When you wrote the code, `somepackage` was at `5.1.2` and `lxml` ran fine with `somepackage==5.1.2`. Now, when `somepackage` was updated to `5.1.3`, it might happen that `lxml` ends up breaking. If you had pinned both `lxml` and `somepackage`, you'd have a set of dependencies that is **known to work together**.

**Pull request merged**
